# yamllint disable rule:key-ordering
name: Get latest release version

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      release_url:
        required: true
        type: string
      username:
        required: true
        type: string
    secrets:
      email:
        required: true

    outputs:
      modified:
        description: Last release version changed
        value: ${{ jobs.get_latest.outputs.modified }}

jobs:
  get_latest:
    runs-on: ubuntu-latest

    outputs:
      modified: ${{ steps.git-check.outputs.modified }}

    steps:
      - uses: actions/checkout@v3
      - name: Fetch release version
        run: >
          curl -sL ${{ inputs.release_url }} |
          jq -r ".tag_name" > latest_release
      - name: Check for modified files
        id: git-check
        run: >
          echo ::set-output name=modified::$([ -z "`git status --porcelain`" ]
          && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "${{ inputs.username }}"
          git config --global user.email "${{ secrets.email }}"
          git add latest_release
          git commit -m "New release version: $(cat latest_release)"
          git push
